export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const SET_HOVER = 'SET_HOVER';
export const SET_LEGEND_POSITION = 'SET_LEGEND_POSITION';
export const SELECT_METRIC = 'SELECT_METRIC';
export const UNSELECT_METRIC = 'UNSELECT_METRIC';
